language: objective-c
matrix:
  include:
    - os: linux
      language: c
    - os: osx

cache:
  directories:
  - $HOME/.ccache

addons:
  apt:
    packages:
      - ccache

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache; fi
  - which ccache
  - ccache -s

script:
  - ccache -s
  - ./build.sh
  - ccache -s
