language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
  allow_failures:
    - os: linux

cache:
  directories:
  - $HOME/.ccache

addons:
  apt:
    packages:
      - ccache
      - libcap-dev
      - g++-multilib
      - gcc-multilib

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache; fi
  - which ccache
  - ccache -s

script:
  - ccache -s
  - ./build.sh
  - ccache -s
